@startuml

hide circle
hide empty attributes
hide empty methods

class Portable{
  prix
  valeurActuelle
  }

class Clavier{
  Type TypeClavier
  touches
  }

enum TypeClavier{
  azerty
  qwerty
  }

class P as "Proprio"{
  nom
  prenom
}

Clavier "1" -- "1" Portable
Clavier -up- TypeClavier
Portable "0..1" -- "0..1" P

@enduml
